---
AWSTemplateFormatVersion: 2010-09-09
Description: A CloudFormation template to a Dynamo Table and IAM role
Resources:
  # IAM Role
  IngestRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
                - ecs.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      RoleName: RoleBookMiddle-PlatformTraining
  # Dynamo Books Table
  BooksDynamoTale:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: book_id
          AttributeType: S
      TableName: BookMiddle-PlatformTraining.Books
      KeySchema:
        - AttributeName: book_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5